gptparams = [
    "searchid",
    "hotel_name",
    "clusterchain",
    "clusterbrand",
    "clustersubbrand",
    "bookingshare",
    "pricepernight",
    "rating",
    "ratingscount",
    "starcategory",
    "mealtype",
    "cancelable",
    "distancetoreference",
    "distancetocity",
    "distancetounderground",
    "distancetobeach",
    "distancetobathing",
    "distancetoairport",
    "distancetotrainstation",
    "roomcategory",
    "roomcategoryid",
    "roomconfiguration",
    "startson",
    "endson",
    "requesttimestamp",
    "numrooms",
    "numadults",
    "numchildren",
    "nights",
    "duration",
    "daystostart",
    "daystostart_bucket",
    "locationtype",
    "locationname",
    "locationid",
    "clusterid",
    "price",
    "popular_location_rank",
    "deviceoutput",
    "ltr_score",
    "amenity_24-Stunden-Rezeption",
    "amenity_24-Stunden-Sicherheitspersonal",
    "amenity_Abendessen",
    "amenity_Abenteuer",
    "amenity_Adapter/Ladegeräte",
    "amenity_Aerobic",
    "amenity_American Express",
    "amenity_Animation (Erwachsene)",
    "amenity_Aparthotel",
    "amenity_Arabisch",
    "amenity_Arbeitsbereich für Arbeit mit Laptop geeignet",
    "amenity_Assistenztiere sind von Gebühren/ Restriktionen ausgeschlossen",
    "amenity_Aufdeckservice",
    "amenity_Aufzug",
    "amenity_Ausflugsinformationen",
    "amenity_Ausgewiesene Raucherbereiche",
    "amenity_Autovermietung",
    "amenity_Außenpool",
    "amenity_Außenpool (saisonal)",
    "amenity_Baby-/ Kinderbetreuung",
    "amenity_Babybadewanne",
    "amenity_Backofen",
    "amenity_Bademantel",
    "amenity_Badewanne oder Dusche",
    "amenity_Balkon",
    "amenity_Bankettsaal",
    "amenity_Bar",
    "amenity_Barrierefrei",
    "amenity_Barrierefreie Dusche",
    "amenity_Beheizter Pool",
    "amenity_Behindertenfreundlich",
    "amenity_Behindertengerechte Parkplätze",
    "amenity_Besichtigungstouren",
    "amenity_Bestätigte Corona-Schutzmaßnahmen",
    "amenity_Betreute Kinderaktivitäten",
    "amenity_Bettwäsche",
    "amenity_Bibliothek",
    "amenity_Bidet",
    "amenity_Billard",
    "amenity_Bosnisch",
    "amenity_Boutique-/Designhotel",
    "amenity_Boutiquen/Läden",
    "amenity_Brettspiele/Puzzle",
    "amenity_Budgetorientiert",
    "amenity_Buggys",
    "amenity_Businesscenter",
    "amenity_Businesshotel",
    "amenity_Bücher",
    "amenity_Bügeleinrichtungen",
    "amenity_Bügelservice",
    "amenity_Café",
    "amenity_Cash (Bargeld)",
    "amenity_Computerarbeitsplatz",
    "amenity_Concierge Service",
    "amenity_Dachterrasse",
    "amenity_Dampfbad",
    "amenity_Darts",
    "amenity_Daunenkissen",
    "amenity_Deckenventilator",
    "amenity_Desinfektion von Geschirr",
    "amenity_Deutsch",
    "amenity_Diners Club",
    "amenity_Discover",
    "amenity_Dusch-Badewannen Kombination",
    "amenity_Dusche",
    "amenity_Duschhocker",
    "amenity_Eigenes Badezimmer",
    "amenity_Einzeln verpackte Essenspakete verfügbar",
    "amenity_Englisch",
    "amenity_Espressomaschine",
    "amenity_Essbereich",
    "amenity_Essen kann auf das Zimmer geliefert werden",
    "amenity_Esstisch",
    "amenity_Eurocard/Mastercard",
    "amenity_Express-Check-in/-out",
    "amenity_Fahrradstellplatz",
    "amenity_Fahrradtouren",
    "amenity_Fahrradvermietung",
    "amenity_Familie",
    "amenity_Familienzimmer vorhanden",
    "amenity_Fax/Kopierer",
    "amenity_Feuerlöscher",
    "amenity_Filme",
    "amenity_Fitness",
    "amenity_Fitnesseinrichtung",
    "amenity_Flachbild-TV",
    "amenity_Flughafenshuttle",
    "amenity_Französisch",
    "amenity_Friseur-/Schönheitssalon",
    "amenity_Frühstück",
    "amenity_Frühstücksbuffet",
    "amenity_Futternapf",
    "amenity_Fußbad",
    "amenity_Fußmassage",
    "amenity_Föhn",
    "amenity_Ganzkörpermassage",
    "amenity_Ganzkörperpackung",
    "amenity_Garten",
    "amenity_Gast kann Zimmerreinigung abmelden",
    "amenity_Gasthaus",
    "amenity_Gefrierschrank",
    "amenity_Geldautomat vor Ort",
    "amenity_Geldwechsel",
    "amenity_Gemeinschaftsbad",
    "amenity_Gemeinschaftsküche",
    "amenity_Gemeinschaftslounge/TV-Bereich",
    "amenity_Gepäckaufbewahrung",
    "amenity_Gesamte Wohneinheit im Erdgeschoß",
    "amenity_Gesamte Wohneinheit ist rollstuhlgerecht",
    "amenity_Geschenkeladen/ Zeitungsstand",
    "amenity_Geschirr für Kinder",
    "amenity_Gesicherte Fahrradstellplätze",
    "amenity_Gesicherte Parkplätze",
    "amenity_Gesichtsbehandlungen",
    "amenity_Getränke/Snackautomat",
    "amenity_Golf/Sport",
    "amenity_Golfplatz (max. 3 km entfernt)",
    "amenity_Golfunterricht",
    "amenity_Grillmöglichkeiten",
    "amenity_Gäste werden auf Gesundheit kontrolliert",
    "amenity_Haarentfernung mit Wachs",
    "amenity_Halboffenes Badezimmer",
    "amenity_Handmassage",
    "amenity_Handschuhe für Gäste verfügbar",
    "amenity_Handtücher",
    "amenity_Hausschuhe",
    "amenity_Haustiere erlaubt",
    "amenity_Haustierfreundliches Hotel",
    "amenity_Heizung",
    "amenity_Heizung im Zimmer steuerbar",
    "amenity_Heiße Quelle",
    "amenity_Hochzeitsservice",
    "amenity_Hotel",
    "amenity_Hundeauslaufplatz",
    "amenity_Hydromassage Dusche",
    "amenity_Hypoallergene Bettware erhältlich",
    "amenity_Höheres WC",
    "amenity_Hörhilfen",
    "amenity_Individuell dekoriert je Zimmer",
    "amenity_Individuelle Möbel je Zimmer",
    "amenity_Infinity-Pool",
    "amenity_Innenpool",
    "amenity_Innenpool (saisonal)",
    "amenity_Investitionen in lokale Nachhaltigkeitsprojekte",
    "amenity_Italienisch",
    "amenity_JCB",
    "amenity_Japanisch",
    "amenity_Kabel TV",
    "amenity_Kaffee/Tee in Gemeinschaftsräumen",
    "amenity_Kanusport",
    "amenity_Kapelle/Schrein",
    "amenity_Karaoke",
    "amenity_Keine Corona-Schutzmaßnahmen",
    "amenity_Keine oder eingeschränkte Verwendung von Plastik-Artikeln (z.B. Strohhalme, Besteck oder Einweg-Artikel)",
    "amenity_Kinder-/Babybetten auf Anfrage",
    "amenity_Kinderbecken",
    "amenity_Kinderbetreuung im Zimmer",
    "amenity_Kinderbücher",
    "amenity_Kinderclub",
    "amenity_Kinderfreundliches Buffet",
    "amenity_Kinderhochstuhl",
    "amenity_Kindermahlzeiten",
    "amenity_Kinderspielplatz",
    "amenity_Kissenauswahl",
    "amenity_Kitchenette",
    "amenity_Klimaanlage im Zimmer",
    "amenity_Klimaanlage im Zimmer steuerbar",
    "amenity_Klimaanlage in allen Zimmern",
    "amenity_Kochplatten/ Herd",
    "amenity_Kochutensilien",
    "amenity_Konferenz- und Veranstaltungsräume",
    "amenity_Kontaktlose Bezahlung",
    "amenity_Kontaktloser Check-In/out",
    "amenity_Kontinentales Frühstück",
    "amenity_Kopfmassage",
    "amenity_Kostenlos parken vor Ort",
    "amenity_Kostenloses Handdesinfektionsmittel",
    "amenity_Kroatisch",
    "amenity_Kunstgalerie im Hotel",
    "amenity_Körperpeeling",
    "amenity_Küche",
    "amenity_Kühl-Gefrierkombination",
    "amenity_Kühlschrank",
    "amenity_Kühlschrank im Gemeinschaftsbereich",
    "amenity_LAN",
    "amenity_LGBT-Freundlich",
    "amenity_Ladestation für Elektro-Autos",
    "amenity_Langzeitparken",
    "amenity_Lebensmittel aus biologischem Anbau",
    "amenity_Lebensmittel aus der Region",
    "amenity_Live-Musik/Performance",
    "amenity_Lokale Karten",
    "amenity_Lunchpakete",
    "amenity_Luxushotel",
    "amenity_Maestro",
    "amenity_Maniküre",
    "amenity_Masken für Gäste verfügbar",
    "amenity_Maskenpflicht",
    "amenity_Massage",
    "amenity_Massage im Zimmer",
    "amenity_Massagestuhl",
    "amenity_Maßnahmen zur Reduzierung des Energieverbrauchs",
    "amenity_Mehrsprachiges Personal",
    "amenity_Mikrowelle",
    "amenity_Mikrowelle im Gemeinschaftsbereich",
    "amenity_Mini-Kühlschrank",
    "amenity_Minibar",
    "amenity_Minigolf",
    "amenity_Minimarkt vor Ort",
    "amenity_Mitarbeiter folgen Regeln des regionalen Standards",
    "amenity_Mitarbeiter tragen Schutzkleidung",
    "amenity_Motto-Dinnerabende",
    "amenity_Nachhaltige Unterkunft",
    "amenity_Nachtclub/DJ",
    "amenity_Nackenmassage",
    "amenity_Nicht rollstuhlgerecht",
    "amenity_Nichtraucherunterkunft",
    "amenity_Nichtraucherzimmer",
    "amenity_Nichtschwimmerbereich",
    "amenity_Niederländisch",
    "amenity_Niedriges Waschbecken",
    "amenity_Niedriges Waschbecken im Bad",
    "amenity_Notrufleine im Bad",
    "amenity_Nur Assistenztiere sind erlaubt",
    "amenity_Nur Hunde sind erlaubt",
    "amenity_Nur Hunde und Katzen sind erlaubt",
    "amenity_Nur für Erwachsene",
    "amenity_Obere Stockwerke mit Fahrstuhl erreichbar",
    "amenity_Outdoorspielgeräte für Kinder",
    "amenity_Paarmassage",
    "amenity_Panoramahotel",
    "amenity_Parken vor Ort",
    "amenity_Parkhaus/Tiefgarage",
    "amenity_Parkplatz außerhalb des Hotelgeländes",
    "amenity_Parkservice",
    "amenity_Pediküre",
    "amenity_Pension",
    "amenity_Pflegeprodukte",
    "amenity_Picknickbereich",
    "amenity_Pillow-Top Matratze",
    "amenity_Polnisch",
    "amenity_Pool",
    "amenity_Pool Cabana",
    "amenity_Pool mit Rampe",
    "amenity_Pool-/Strandtücher",
    "amenity_Poolbar",
    "amenity_Portier/Hotelpage",
    "amenity_Portugiesisch",
    "amenity_Premium Bettwaren",
    "amenity_Privater Check-in/-out",
    "amenity_Privater Strand",
    "amenity_Privates Abendessen",
    "amenity_Privates Tauchbecken",
    "amenity_Privatstrand in der Nähe",
    "amenity_Programm zur Reduzierung von Lebensmittelabfällen",
    "amenity_Pub Crawl",
    "amenity_Radfahren",
    "amenity_Raucher und Nichtraucherzimmer",
    "amenity_Raucherzimmer",
    "amenity_Rauchmelder",
    "amenity_Recycling",
    "amenity_Regendusche",
    "amenity_Reinigung mit Desinfektionsmittel",
    "amenity_Reinigungsmittel gegen Coronaviren",
    "amenity_Reiseführer oder Empfehlungen",
    "amenity_Reiten",
    "amenity_Resort",
    "amenity_Restaurant",
    "amenity_Rezeption",
    "amenity_Rollstuhlgerecht",
    "amenity_Rollstühle verfügbar",
    "amenity_Romantik/Flitterwochen",
    "amenity_Rumänisch",
    "amenity_Russisch",
    "amenity_Räumliche Trennung von Gästen und Mitarbeitern in Hauptkontaktzonen",
    "amenity_Rückenmassage",
    "amenity_Safe an der Rezeption",
    "amenity_Safe im Zimmer",
    "amenity_Safe in Laptopgröße",
    "amenity_Satelliten-TV",
    "amenity_Sauna",
    "amenity_Schallisolierung",
    "amenity_Schlafsofa",
    "amenity_Schlafzimmer",
    "amenity_Schließfächer",
    "amenity_Schrank",
    "amenity_Schreibtisch",
    "amenity_Schutzkleidung für Gäste verfügbar",
    "amenity_Schwimmbad",
    "amenity_Seife",
    "amenity_Serbisch",
    "amenity_Shampoo",
    "amenity_Shopping",
    "amenity_Shuttle in die Umgebung",
    "amenity_Shuttle zum Bahnhof",
    "amenity_Shuttle zur Fähre",
    "amenity_Shuttleservice",
    "amenity_Sicherheitsalarm",
    "amenity_Sitzecke",
    "amenity_Slowakisch",
    "amenity_Smart TV",
    "amenity_Snackbar",
    "amenity_Social Distancing Maßnahmen",
    "amenity_Solarium",
    "amenity_Sonnenschirme",
    "amenity_Sonnenstühle/-liegen",
    "amenity_Spa & Wellnesscenter",
    "amenity_Spa-Anwendungen",
    "amenity_Spa/Entspannung",
    "amenity_Spanisch",
    "amenity_Speisen für spezielle Ernährungsbedürfnisse",
    "amenity_Spielbereich",
    "amenity_Spiele für Kinder",
    "amenity_Spielhalle",
    "amenity_Spielzeug",
    "amenity_Spülmaschine",
    "amenity_Strand",
    "amenity_Strand Cabana",
    "amenity_Strandbar",
    "amenity_Strandhotel",
    "amenity_Streaming-Dienste (z.B. Netflix)",
    "amenity_Streaming-Service",
    "amenity_Strom aus erneuerbaren Energien",
    "amenity_Städtereise",
    "amenity_TV",
    "amenity_Tagesbett",
    "amenity_Tauchbecken",
    "amenity_Tee-/Kaffeezubereiter",
    "amenity_Teile des CO²-Ausstoßes werden durch Zertifikate ausgeglichen",
    "amenity_Telefon",
    "amenity_Tennisausrüstung",
    "amenity_Tennisplatz",
    "amenity_Terrasse",
    "amenity_Thailändisch",
    "amenity_Ticketservice",
    "amenity_Tierkörbchen",
    "amenity_Tischtennis",
    "amenity_Toilettenpapier",
    "amenity_Touren/Kurse über die örtliche Kultur",
    "amenity_Tschechisch",
    "amenity_Ungarisch",
    "amenity_Unterkunft wird von professionellem Reinigungsservice gereinigt",
    "amenity_Vegan",
    "amenity_Vegetarisch",
    "amenity_Ventilator",
    "amenity_Veranda/Terrasse",
    "amenity_Verdunkelungsvorhänge",
    "amenity_Versiegelung des Raums nach Reinigung",
    "amenity_Videoüberwachung der Außenbereiche der Unterkunft",
    "amenity_Videoüberwachung in Gemeinschaftsbereichen",
    "amenity_Visa",
    "amenity_Visuelle Hilfe: Braille",
    "amenity_Visuelle Hilfe: fühlbare Zeichen",
    "amenity_Vollwertiges Frühstück",
    "amenity_WC mit Haltegriffen",
    "amenity_WLAN",
    "amenity_Wandern",
    "amenity_Waschsalon/Wäscheservice",
    "amenity_Wassereinsparende Badezimmer-Einrichtungen",
    "amenity_Wasserkocher",
    "amenity_Wasserpark",
    "amenity_Wasserrutsche",
    "amenity_Wasserspielzeug für Kinder",
    "amenity_Wassersportmöglichkeiten vor Ort",
    "amenity_Wellness",
    "amenity_Wellnessangebote",
    "amenity_Wellnessbehandlungsraum/-räume\xa0",
    "amenity_Wellnesshotel",
    "amenity_Wellnesslounge/Ruhebereich",
    "amenity_Whirlpool",
    "amenity_Whirlpool-Badewanne",
    "amenity_Whirlpool/Jacuzzi",
    "amenity_Wickeltisch",
    "amenity_Wohnzimmer",
    "amenity_Wäsche wird nach regionalem Standard gewaschen",
    "amenity_Yoga",
    "amenity_Zahnbürste",
    "amenity_Zeitlicher Abstand zwischen Aufenthalten von Gästen eingeführt",
    "amenity_Zeitung",
    "amenity_Zeitungen in der Lobby",
    "amenity_Zimmer mit Verbindungstür",
    "amenity_Zimmerreinigung",
    "amenity_Zimmerreinigung (eingeschränkt)",
    "amenity_Zimmerservice",
    "amenity_Zimmerservice (eingeschränkt)",
    "amenity_Zugang über außengelegene Gänge",
    "amenity_Zustellbett auf Anfrage",
    "amenity_Zustellbetten",
    "amenity_direkter Strandzugang (privater Strand)",
    "amenity_iPod-Dockingstation",
    "amenity_ländlich",
    "amenity_Übergroße Badewanne",
]


amenities_german = [
    "amenity_24-Stunden-Rezeption",
    "amenity_24-Stunden-Sicherheitspersonal",
    "amenity_Abendessen",
    "amenity_Abenteuer",
    "amenity_Adapter/Ladegeräte",
    "amenity_Aerobic",
    "amenity_American Express",
    "amenity_Animation (Erwachsene)",
    "amenity_Aparthotel",
    "amenity_Arabisch",
    "amenity_Arbeitsbereich für Arbeit mit Laptop geeignet",
    "amenity_Assistenztiere sind von Gebühren/ Restriktionen ausgeschlossen",
    "amenity_Aufdeckservice",
    "amenity_Aufzug",
    "amenity_Ausflugsinformationen",
    "amenity_Ausgewiesene Raucherbereiche",
    "amenity_Autovermietung",
    "amenity_Außenpool",
    "amenity_Außenpool (saisonal)",
    "amenity_Baby-/ Kinderbetreuung",
    "amenity_Babybadewanne",
    "amenity_Backofen",
    "amenity_Bademantel",
    "amenity_Badewanne oder Dusche",
    "amenity_Balkon",
    "amenity_Bankettsaal",
    "amenity_Bar",
    "amenity_Barrierefrei",
    "amenity_Barrierefreie Dusche",
    "amenity_Beheizter Pool",
    "amenity_Behindertenfreundlich",
    "amenity_Behindertengerechte Parkplätze",
    "amenity_Besichtigungstouren",
    "amenity_Bestätigte Corona-Schutzmaßnahmen",
    "amenity_Betreute Kinderaktivitäten",
    "amenity_Bettwäsche",
    "amenity_Bibliothek",
    "amenity_Bidet",
    "amenity_Billard",
    "amenity_Bosnisch",
    "amenity_Boutique-/Designhotel",
    "amenity_Boutiquen/Läden",
    "amenity_Brettspiele/Puzzle",
    "amenity_Budgetorientiert",
    "amenity_Buggys",
    "amenity_Businesscenter",
    "amenity_Businesshotel",
    "amenity_Bücher",
    "amenity_Bügeleinrichtungen",
    "amenity_Bügelservice",
    "amenity_Café",
    "amenity_Cash (Bargeld)",
    "amenity_Computerarbeitsplatz",
    "amenity_Concierge Service",
    "amenity_Dachterrasse",
    "amenity_Dampfbad",
    "amenity_Darts",
    "amenity_Daunenkissen",
    "amenity_Deckenventilator",
    "amenity_Desinfektion von Geschirr",
    "amenity_Deutsch",
    "amenity_Diners Club",
    "amenity_Discover",
    "amenity_Dusch-Badewannen Kombination",
    "amenity_Dusche",
    "amenity_Duschhocker",
    "amenity_Eigenes Badezimmer",
    "amenity_Einzeln verpackte Essenspakete verfügbar",
    "amenity_Englisch",
    "amenity_Espressomaschine",
    "amenity_Essbereich",
    "amenity_Essen kann auf das Zimmer geliefert werden",
    "amenity_Esstisch",
    "amenity_Eurocard/Mastercard",
    "amenity_Express-Check-in/-out",
    "amenity_Fahrradstellplatz",
    "amenity_Fahrradtouren",
    "amenity_Fahrradvermietung",
    "amenity_Familie",
    "amenity_Familienzimmer vorhanden",
    "amenity_Fax/Kopierer",
    "amenity_Feuerlöscher",
    "amenity_Filme",
    "amenity_Fitness",
    "amenity_Fitnesseinrichtung",
    "amenity_Flachbild-TV",
    "amenity_Flughafenshuttle",
    "amenity_Französisch",
    "amenity_Friseur-/Schönheitssalon",
    "amenity_Frühstück",
    "amenity_Frühstücksbuffet",
    "amenity_Futternapf",
    "amenity_Fußbad",
    "amenity_Fußmassage",
    "amenity_Föhn",
    "amenity_Ganzkörpermassage",
    "amenity_Ganzkörperpackung",
    "amenity_Garten",
    "amenity_Gast kann Zimmerreinigung abmelden",
    "amenity_Gasthaus",
    "amenity_Gefrierschrank",
    "amenity_Geldautomat vor Ort",
    "amenity_Geldwechsel",
    "amenity_Gemeinschaftsbad",
    "amenity_Gemeinschaftsküche",
    "amenity_Gemeinschaftslounge/TV-Bereich",
    "amenity_Gepäckaufbewahrung",
    "amenity_Gesamte Wohneinheit im Erdgeschoß",
    "amenity_Gesamte Wohneinheit ist rollstuhlgerecht",
    "amenity_Geschenkeladen/ Zeitungsstand",
    "amenity_Geschirr für Kinder",
    "amenity_Gesicherte Fahrradstellplätze",
    "amenity_Gesicherte Parkplätze",
    "amenity_Gesichtsbehandlungen",
    "amenity_Getränke/Snackautomat",
    "amenity_Golf/Sport",
    "amenity_Golfplatz (max. 3 km entfernt)",
    "amenity_Golfunterricht",
    "amenity_Grillmöglichkeiten",
    "amenity_Gäste werden auf Gesundheit kontrolliert",
    "amenity_Haarentfernung mit Wachs",
    "amenity_Halboffenes Badezimmer",
    "amenity_Handmassage",
    "amenity_Handschuhe für Gäste verfügbar",
    "amenity_Handtücher",
    "amenity_Hausschuhe",
    "amenity_Haustiere erlaubt",
    "amenity_Haustierfreundliches Hotel",
    "amenity_Heizung",
    "amenity_Heizung im Zimmer steuerbar",
    "amenity_Heiße Quelle",
    "amenity_Hochzeitsservice",
    "amenity_Hotel",
    "amenity_Hundeauslaufplatz",
    "amenity_Hydromassage Dusche",
    "amenity_Hypoallergene Bettware erhältlich",
    "amenity_Höheres WC",
    "amenity_Hörhilfen",
    "amenity_Individuell dekoriert je Zimmer",
    "amenity_Individuelle Möbel je Zimmer",
    "amenity_Infinity-Pool",
    "amenity_Innenpool",
    "amenity_Innenpool (saisonal)",
    "amenity_Investitionen in lokale Nachhaltigkeitsprojekte",
    "amenity_Italienisch",
    "amenity_JCB",
    "amenity_Japanisch",
    "amenity_Kabel TV",
    "amenity_Kaffee/Tee in Gemeinschaftsräumen",
    "amenity_Kanusport",
    "amenity_Kapelle/Schrein",
    "amenity_Karaoke",
    "amenity_Keine Corona-Schutzmaßnahmen",
    "amenity_Keine oder eingeschränkte Verwendung von Plastik-Artikeln (z.B. Strohhalme, Besteck oder Einweg-Artikel)",
    "amenity_Kinder-/Babybetten auf Anfrage",
    "amenity_Kinderbecken",
    "amenity_Kinderbetreuung im Zimmer",
    "amenity_Kinderbücher",
    "amenity_Kinderclub",
    "amenity_Kinderfreundliches Buffet",
    "amenity_Kinderhochstuhl",
    "amenity_Kindermahlzeiten",
    "amenity_Kinderspielplatz",
    "amenity_Kissenauswahl",
    "amenity_Kitchenette",
    "amenity_Klimaanlage im Zimmer",
    "amenity_Klimaanlage im Zimmer steuerbar",
    "amenity_Klimaanlage in allen Zimmern",
    "amenity_Kochplatten/ Herd",
    "amenity_Kochutensilien",
    "amenity_Konferenz- und Veranstaltungsräume",
    "amenity_Kontaktlose Bezahlung",
    "amenity_Kontaktloser Check-In/out",
    "amenity_Kontinentales Frühstück",
    "amenity_Kopfmassage",
    "amenity_Kostenlos parken vor Ort",
    "amenity_Kostenloses Handdesinfektionsmittel",
    "amenity_Kroatisch",
    "amenity_Kunstgalerie im Hotel",
    "amenity_Körperpeeling",
    "amenity_Küche",
    "amenity_Kühl-Gefrierkombination",
    "amenity_Kühlschrank",
    "amenity_Kühlschrank im Gemeinschaftsbereich",
    "amenity_LAN",
    "amenity_LGBT-Freundlich",
    "amenity_Ladestation für Elektro-Autos",
    "amenity_Langzeitparken",
    "amenity_Lebensmittel aus biologischem Anbau",
    "amenity_Lebensmittel aus der Region",
    "amenity_Live-Musik/Performance",
    "amenity_Lokale Karten",
    "amenity_Lunchpakete",
    "amenity_Luxushotel",
    "amenity_Maestro",
    "amenity_Maniküre",
    "amenity_Masken für Gäste verfügbar",
    "amenity_Maskenpflicht",
    "amenity_Massage",
    "amenity_Massage im Zimmer",
    "amenity_Massagestuhl",
    "amenity_Maßnahmen zur Reduzierung des Energieverbrauchs",
    "amenity_Mehrsprachiges Personal",
    "amenity_Mikrowelle",
    "amenity_Mikrowelle im Gemeinschaftsbereich",
    "amenity_Mini-Kühlschrank",
    "amenity_Minibar",
    "amenity_Minigolf",
    "amenity_Minimarkt vor Ort",
    "amenity_Mitarbeiter folgen Regeln des regionalen Standards",
    "amenity_Mitarbeiter tragen Schutzkleidung",
    "amenity_Motto-Dinnerabende",
    "amenity_Nachhaltige Unterkunft",
    "amenity_Nachtclub/DJ",
    "amenity_Nackenmassage",
    "amenity_Nicht rollstuhlgerecht",
    "amenity_Nichtraucherunterkunft",
    "amenity_Nichtraucherzimmer",
    "amenity_Nichtschwimmerbereich",
    "amenity_Niederländisch",
    "amenity_Niedriges Waschbecken",
    "amenity_Niedriges Waschbecken im Bad",
    "amenity_Notrufleine im Bad",
    "amenity_Nur Assistenztiere sind erlaubt",
    "amenity_Nur Hunde sind erlaubt",
    "amenity_Nur Hunde und Katzen sind erlaubt",
    "amenity_Nur für Erwachsene",
    "amenity_Obere Stockwerke mit Fahrstuhl erreichbar",
    "amenity_Outdoorspielgeräte für Kinder",
    "amenity_Paarmassage",
    "amenity_Panoramahotel",
    "amenity_Parken vor Ort",
    "amenity_Parkhaus/Tiefgarage",
    "amenity_Parkplatz außerhalb des Hotelgeländes",
    "amenity_Parkservice",
    "amenity_Pediküre",
    "amenity_Pension",
    "amenity_Pflegeprodukte",
    "amenity_Picknickbereich",
    "amenity_Pillow-Top Matratze",
    "amenity_Polnisch",
    "amenity_Pool",
    "amenity_Pool Cabana",
    "amenity_Pool mit Rampe",
    "amenity_Pool-/Strandtücher",
    "amenity_Poolbar",
    "amenity_Portier/Hotelpage",
    "amenity_Portugiesisch",
    "amenity_Premium Bettwaren",
    "amenity_Privater Check-in/-out",
    "amenity_Privater Strand",
    "amenity_Privates Abendessen",
    "amenity_Privates Tauchbecken",
    "amenity_Privatstrand in der Nähe",
    "amenity_Programm zur Reduzierung von Lebensmittelabfällen",
    "amenity_Pub Crawl",
    "amenity_Radfahren",
    "amenity_Raucher und Nichtraucherzimmer",
    "amenity_Raucherzimmer",
    "amenity_Rauchmelder",
    "amenity_Recycling",
    "amenity_Regendusche",
    "amenity_Reinigung mit Desinfektionsmittel",
    "amenity_Reinigungsmittel gegen Coronaviren",
    "amenity_Reiseführer oder Empfehlungen",
    "amenity_Reiten",
    "amenity_Resort",
    "amenity_Restaurant",
    "amenity_Rezeption",
    "amenity_Rollstuhlgerecht",
    "amenity_Rollstühle verfügbar",
    "amenity_Romantik/Flitterwochen",
    "amenity_Rumänisch",
    "amenity_Russisch",
    "amenity_Räumliche Trennung von Gästen und Mitarbeitern in Hauptkontaktzonen",
    "amenity_Rückenmassage",
    "amenity_Safe an der Rezeption",
    "amenity_Safe im Zimmer",
    "amenity_Safe in Laptopgröße",
    "amenity_Satelliten-TV",
    "amenity_Sauna",
    "amenity_Schallisolierung",
    "amenity_Schlafsofa",
    "amenity_Schlafzimmer",
    "amenity_Schließfächer",
    "amenity_Schrank",
    "amenity_Schreibtisch",
    "amenity_Schutzkleidung für Gäste verfügbar",
    "amenity_Schwimmbad",
    "amenity_Seife",
    "amenity_Serbisch",
    "amenity_Shampoo",
    "amenity_Shopping",
    "amenity_Shuttle in die Umgebung",
    "amenity_Shuttle zum Bahnhof",
    "amenity_Shuttle zur Fähre",
    "amenity_Shuttleservice",
    "amenity_Sicherheitsalarm",
    "amenity_Sitzecke",
    "amenity_Slowakisch",
    "amenity_Smart TV",
    "amenity_Snackbar",
    "amenity_Social Distancing Maßnahmen",
    "amenity_Solarium",
    "amenity_Sonnenschirme",
    "amenity_Sonnenstühle/-liegen",
    "amenity_Spa & Wellnesscenter",
    "amenity_Spa-Anwendungen",
    "amenity_Spa/Entspannung",
    "amenity_Spanisch",
    "amenity_Speisen für spezielle Ernährungsbedürfnisse",
    "amenity_Spielbereich",
    "amenity_Spiele für Kinder",
    "amenity_Spielhalle",
    "amenity_Spielzeug",
    "amenity_Spülmaschine",
    "amenity_Strand",
    "amenity_Strand Cabana",
    "amenity_Strandbar",
    "amenity_Strandhotel",
    "amenity_Streaming-Dienste (z.B. Netflix)",
    "amenity_Streaming-Service",
    "amenity_Strom aus erneuerbaren Energien",
    "amenity_Städtereise",
    "amenity_TV",
    "amenity_Tagesbett",
    "amenity_Tauchbecken",
    "amenity_Tee-/Kaffeezubereiter",
    "amenity_Teile des CO²-Ausstoßes werden durch Zertifikate ausgeglichen",
    "amenity_Telefon",
    "amenity_Tennisausrüstung",
    "amenity_Tennisplatz",
    "amenity_Terrasse",
    "amenity_Thailändisch",
    "amenity_Ticketservice",
    "amenity_Tierkörbchen",
    "amenity_Tischtennis",
    "amenity_Toilettenpapier",
    "amenity_Touren/Kurse über die örtliche Kultur",
    "amenity_Tschechisch",
    "amenity_Ungarisch",
    "amenity_Unterkunft wird von professionellem Reinigungsservice gereinigt",
    "amenity_Vegan",
    "amenity_Vegetarisch",
    "amenity_Ventilator",
    "amenity_Veranda/Terrasse",
    "amenity_Verdunkelungsvorhänge",
    "amenity_Versiegelung des Raums nach Reinigung",
    "amenity_Videoüberwachung der Außenbereiche der Unterkunft",
    "amenity_Videoüberwachung in Gemeinschaftsbereichen",
    "amenity_Visa",
    "amenity_Visuelle Hilfe: Braille",
    "amenity_Visuelle Hilfe: fühlbare Zeichen",
    "amenity_Vollwertiges Frühstück",
    "amenity_WC mit Haltegriffen",
    "amenity_WLAN",
    "amenity_Wandern",
    "amenity_Waschsalon/Wäscheservice",
    "amenity_Wassereinsparende Badezimmer-Einrichtungen",
    "amenity_Wasserkocher",
    "amenity_Wasserpark",
    "amenity_Wasserrutsche",
    "amenity_Wasserspielzeug für Kinder",
    "amenity_Wassersportmöglichkeiten vor Ort",
    "amenity_Wellness",
    "amenity_Wellnessangebote",
    "amenity_Wellnessbehandlungsraum/-räume ",
    "amenity_Wellnesshotel",
    "amenity_Wellnesslounge/Ruhebereich",
    "amenity_Whirlpool",
    "amenity_Whirlpool-Badewanne",
    "amenity_Whirlpool/Jacuzzi",
    "amenity_Wickeltisch",
    "amenity_Wohnzimmer",
    "amenity_Wäsche wird nach regionalem Standard gewaschen",
    "amenity_Yoga",
    "amenity_Zahnbürste",
    "amenity_Zeitlicher Abstand zwischen Aufenthalten ion Gästen eingeführt",
    "amenity_Zeitung",
    "amenity_Zeitungen in der Lobby",
    "amenity_Zimmer mit Verbindungstür",
    "amenity_Zimmerreinigung",
    "amenity_Zimmerreinigung (eingeschränkt)",
    "amenity_Zimmerservice",
    "amenity_Zimmerservice (eingeschränkt)",
    "amenity_Zugang über außengelegene Gänge",
    "amenity_Zustellbett auf Anfrage",
    "amenity_Zustellbetten",
    "amenity_direkter Strandzugang (privater Strand)",
    "amenity_iPod-Dockingstation",
    "amenity_ländlich",
    "amenity_Übergroße Badewanne",
]


amenities = [
    "twenty_four_hour_reception",
    "twenty_four_hour_security_staff",
    "dinner",
    "adventure",
    "adapters_chargers",
    "aerobics",
    "american_express",
    "adult_animation",
    "aparthotel",
    "arabic",
    "laptop_friendly_workspace",
    "assistance_animals_exempt_from_fees_or_restrictions",
    "turndown_service",
    "elevator",
    "tour_information",
    "designated_smoking_areas",
    "car_rental",
    "outdoor_pool",
    "seasonal_outdoor_pool",
    "babysitting_child_services",
    "baby_bathtub",
    "oven",
    "bathrobe",
    "bathtub_or_shower",
    "balcony",
    "banquet_hall",
    "bar",
    "accessible",
    "accessible_shower",
    "heated_pool",
    "disabled_friendly",
    "accessible_parking",
    "sightseeing_tours",
    "confirmed_covid_protection_measures",
    "supervised_kids_activities",
    "bed_linen",
    "library",
    "bidet",
    "billiards",
    "bosnian",
    "boutique_design_hotel",
    "boutiques_shops",
    "board_games_puzzles",
    "budget_friendly",
    "strollers",
    "business_center",
    "business_hotel",
    "books",
    "ironing_facilities",
    "ironing_service",
    "cafe",
    "cash",
    "computer_workstation",
    "concierge_service",
    "rooftop_terrace",
    "steam_bath",
    "darts",
    "down_pillows",
    "ceiling_fan",
    "sanitized_dishware",
    "german",
    "diners_club",
    "discover",
    "bathtub_shower_combination",
    "shower",
    "shower_seat",
    "private_bathroom",
    "individually_packaged_meals_available",
    "english",
    "espresso_machine",
    "dining_area",
    "room_service_meals_available",
    "dining_table",
    "mastercard",
    "express_check_in_out",
    "bike_parking",
    "bike_tours",
    "bike_rental",
    "family",
    "family_rooms_available",
    "fax_photocopying",
    "fire_extinguisher",
    "movies",
    "fitness",
    "fitness_facilities",
    "flat_screen_tv",
    "airport_shuttle",
    "french",
    "hair_beauty_salon",
    "breakfast",
    "breakfast_buffet",
    "pet_bowl",
    "foot_bath",
    "foot_massage",
    "hair_dryer",
    "full_body_massage",
    "full_body_wrap",
    "garden",
    "guest_can_opt_out_of_cleaning",
    "guesthouse",
    "freezer",
    "atm_on_site",
    "currency_exchange",
    "shared_bathroom",
    "shared_kitchen",
    "shared_lounge_tv_area",
    "luggage_storage",
    "ground_floor_unit",
    "wheelchair_accessible_unit",
    "gift_shop_newsstand",
    "childrens_dishware",
    "secure_bike_storage",
    "secure_parking",
    "facial_treatments",
    "vending_machine_snacks_drinks",
    "golf_sport",
    "golf_course_within_3km",
    "golf_lessons",
    "bbq_facilities",
    "health_screening_for_guests",
    "waxing_services",
    "semi_open_bathroom",
    "hand_massage",
    "gloves_available_for_guests",
    "towels",
    "slippers",
    "pets_allowed",
    "pet_friendly_hotel",
    "heating",
    "individually_controlled_heating",
    "hot_spring",
    "wedding_services",
    "hotel",
    "dog_run_area",
    "hydromassage_shower",
    "hypoallergenic_bedding_available",
    "raised_toilet",
    "hearing_aids",
    "individually_decorated_rooms",
    "individually_furnished_rooms",
    "infinity_pool",
    "indoor_pool",
    "seasonal_indoor_pool",
    "investment_in_local_sustainability_projects",
    "italian",
    "jcb",
    "japanese",
    "cable_tv",
    "coffee_tea_in_common_areas",
    "canoeing",
    "chapel_shrine",
    "karaoke",
    "no_covid_protection_measures",
    "limited_single_use_plastic_items",
    "baby_cots_on_request",
    "kids_pool",
    "in_room_childcare",
    "childrens_books",
    "kids_club",
    "child_friendly_buffet",
    "high_chair",
    "kids_meals",
    "playground",
    "pillow_menu",
    "kitchenette",
    "in_room_air_conditioning",
    "individually_controlled_air_conditioning",
    "air_conditioning_in_all_rooms",
    "stovetop",
    "cooking_utensils",
    "conference_event_rooms",
    "contactless_payment",
    "contactless_check_in_out",
    "continental_breakfast",
    "head_massage",
    "free_onsite_parking",
    "free_hand_sanitizer",
    "croatian",
    "hotel_art_gallery",
    "body_scrub",
    "kitchen",
    "fridge_freezer",
    "refrigerator",
    "shared_refrigerator",
    "lan",
    "lgbt_friendly",
    "ev_charging_station",
    "long_term_parking",
    "organic_food",
    "locally_sourced_food",
    "live_music_performance",
    "local_maps",
    "packed_lunches",
    "luxury_hotel",
    "maestro",
    "manicure",
    "masks_available_for_guests",
    "mask_requirement",
    "massage",
    "in_room_massage",
    "massage_chair",
    "energy_reduction_measures",
    "multilingual_staff",
    "microwave",
    "shared_microwave",
    "mini_fridge",
    "minibar",
    "mini_golf",
    "onsite_convenience_store",
    "staff_follow_local_safety_guidelines",
    "staff_wear_protective_equipment",
    "theme_dinner_nights",
    "sustainable_accommodation",
    "nightclub_dj",
    "neck_massage",
    "not_wheelchair_accessible",
    "non_smoking_accommodation",
    "non_smoking_rooms",
    "shallow_pool_area",
    "dutch",
    "low_sink",
    "low_bathroom_sink",
    "bathroom_emergency_pull_cord",
    "service_animals_only",
    "dogs_only",
    "dogs_and_cats_only",
    "adults_only",
    "upper_floors_accessible_by_elevator",
    "outdoor_play_equipment_for_kids",
    "couples_massage",
    "panorama_hotel",
    "onsite_parking",
    "parking_garage",
    "offsite_parking",
    "valet_parking",
    "pedicure",
    "guesthouse_lodging",
    "toiletries",
    "picnic_area",
    "pillow_top_mattress",
    "polish",
    "pool",
    "pool_cabana",
    "pool_ramp",
    "pool_beach_towels",
    "pool_bar",
    "porter_bellhop",
    "portuguese",
    "premium_bedding",
    "private_check_in_out",
    "private_beach",
    "private_dinner",
    "private_plunge_pool",
    "nearby_private_beach",
    "food_waste_reduction_program",
    "pub_crawl",
    "cycling",
    "smoking_and_non_smoking_rooms",
    "smoking_rooms",
    "smoke_detector",
    "recycling",
    "rain_shower",
    "disinfectant_cleaning",
    "anti_covid_cleaning_supplies",
    "tour_guides_or_recommendations",
    "horseback_riding",
    "resort",
    "restaurant",
    "reception",
    "wheelchair_accessible",
    "wheelchairs_available",
    "romantic_honeymoon",
    "romanian",
    "russian",
    "guest_staff_barriers_in_main_areas",
    "back_massage",
    "front_desk_safe",
    "in_room_safe",
    "laptop_safe",
    "satellite_tv",
    "sauna",
    "soundproofing",
    "sofa_bed",
    "bedroom",
    "lockers",
    "wardrobe",
    "desk",
    "protective_gear_available_for_guests",
    "swimming_pool",
    "soap",
    "serbian",
    "shampoo",
    "shopping",
    "local_area_shuttle",
    "station_shuttle",
    "ferry_shuttle",
    "shuttle_service",
    "security_alarm",
    "sitting_area",
    "slovak",
    "smart_tv",
    "snack_bar",
    "social_distancing_measures",
    "solarium",
    "sun_umbrellas",
    "sun_loungers_beach_chairs",
    "spa_wellness_center",
    "spa_treatments",
    "spa_relaxation",
    "spanish",
    "special_diet_meals",
    "play_area",
    "kids_games",
    "game_room",
    "toys",
    "dishwasher",
    "beach",
    "beach_cabana",
    "beach_bar",
    "beachfront_hotel",
    "streaming_services",
    "streaming_service",
    "renewable_energy_used",
    "city_trip",
    "tv",
    "daybed",
    "plunge_pool",
    "tea_coffee_maker",
    "carbon_offset_certificates",
    "telephone",
    "tennis_equipment",
    "tennis_court",
    "terrace",
    "thai",
    "ticket_service",
    "pet_basket",
    "table_tennis",
    "toilet_paper",
    "local_culture_tours_classes",
    "czech",
    "hungarian",
    "professional_cleaning_service",
    "vegan",
    "vegetarian",
    "fan",
    "veranda_terrace",
    "blackout_curtains",
    "room_sealed_after_cleaning",
    "outdoor_surveillance",
    "indoor_surveillance",
    "visa",
    "braille_signs",
    "tactile_signs",
    "full_breakfast",
    "toilet_with_grab_rails",
    "wifi",
    "hiking",
    "laundry_service",
    "water_saving_bathroom_fixtures",
    "electric_kettle",
    "water_park",
    "waterslide",
    "kids_water_toys",
    "watersports_on_site",
    "wellness",
    "wellness_offers",
    "spa_treatment_rooms",
    "wellness_hotel",
    "wellness_lounge_relax_area",
    "hot_tub",
    "jacuzzi_bathtub",
    "hot_tub_jacuzzi",
    "changing_table",
    "living_room",
    "laundry_follow_local_guidelines",
    "yoga",
    "toothbrush",
    "guest_buffer_time",
    "newspaper",
    "lobby_newspapers",
    "connecting_rooms",
    "room_cleaning",
    "limited_room_cleaning",
    "room_service",
    "limited_room_service",
    "exterior_corridors",
    "extra_bed_on_request",
    "extra_beds",
    "private_beach_access",
    "ipod_docking_station",
    "rural",
    "oversized_bathtub",
]
